import type { Patient } from '@/shared/types/patient';

const patients: Patient[] = [
  {
    id: '8f1a2e30-9e6d-4b18-9cb7-8b8e7a62b5b4',
    first_name: 'Elena',
    last_name: 'Martinez',
    email: 'elena.martinez@example.com',
    phone: '+1-202-555-0143',
    gender: 'female',
    birth_date: '1985-06-22',
    address: {
      street: '456 Maple Ave',
      city: 'New York',
      zip_code: '10001',
    },
    national_id: 'NY12345678',
    insurance_number: 'INS-2024-8712',
    registration_date: '2024-11-12T10:30:00Z',
    profile_image: 'https://example.com/uploads/patients/elena-martinez.jpg',
    preferred_language: 'en',
    contact_preference: 'email',
    emergency_contact: {
      name: 'Carlos Martinez',
      relation: 'husband',
      phone: '+1-202-555-0110',
    },
    notes:
      'Patient has a history of migraines. Observed mild anxiety. Prefers morning appointments.',
    files: [
      'https://example.com/files/mri_scan_elena_2024.pdf',
      'https://example.com/files/bloodwork_results_2024-11-10.jpg',
    ],
    appointments: ['apt-2024-11-10-001', 'apt-2025-01-05-004'],
    medical_flags: ['migraine', 'anxiety'],
    allergies: [
      {
        substance: 'penicillin',
        reaction: 'rash and difficulty breathing',
        severity: 'severe',
      },
    ],
    medications: [
      {
        name: 'Ibuprofen',
        dosage: '200mg twice a day',
        start_date: '2025-01-01',
        end_date: '2025-02-01',
        prescribed_by: 'dr-231',
      },
      {
        name: 'Propranolol',
        dosage: '40mg daily',
        start_date: '2024-10-01',
        end_date: '2025-10-01',
        prescribed_by: 'dr-145',
      },
    ],
    conditions: ['migraine', 'mild anxiety'],
    consent_to_contact: true,
    consent_signed_date: '2024-11-12',
    status: 'active',
    tags: ['VIP', 'high-risk'],
  },
  {
    id: 'd27fa8e1-2d24-40ee-9825-994d2a59a607',
    first_name: 'Michael',
    last_name: 'Nguyen',
    email: 'michael.nguyen@example.com',
    phone: '+1-312-555-0198',
    gender: 'male',
    birth_date: '1972-04-10',
    address: {
      street: '23 Cedar Street',
      city: 'Chicago',
      zip_code: '60616',
    },
    national_id: 'IL74839204',
    insurance_number: 'CH-7788-0092',
    registration_date: '2023-07-08T14:00:00Z',
    profile_image: 'https://example.com/uploads/patients/michael-nguyen.png',
    preferred_language: 'en',
    contact_preference: 'phone',
    emergency_contact: {
      name: 'Linda Nguyen',
      relation: 'wife',
      phone: '+1-312-555-0184',
    },
    notes: 'Diagnosed with type 2 diabetes. Needs regular glucose monitoring.',
    files: [],
    appointments: ['apt-2024-08-14-002'],
    medical_flags: ['diabetes'],
    allergies: [],
    medications: [
      {
        name: 'Metformin',
        dosage: '500mg twice a day',
        start_date: '2024-01-15',
        end_date: '2025-01-15',
        prescribed_by: 'dr-101',
      },
    ],
    conditions: ['type 2 diabetes'],
    consent_to_contact: true,
    consent_signed_date: '2023-07-08',
    status: 'active',
    tags: ['chronic', 'monitoring'],
  },
  {
    id: '78fcea64-b0c9-4c79-a242-3df019fd61da',
    first_name: 'Fatima',
    last_name: 'Al-Farsi',
    email: 'fatima.alfarsi@example.com',
    phone: '+44-20-7946-0958',
    gender: 'female',
    birth_date: '1991-09-03',
    address: {
      street: "12 Queen's Crescent",
      city: 'London',
      zip_code: 'NW5 4ED',
    },
    national_id: 'UK92837465',
    insurance_number: 'NHS-48201938',
    registration_date: '2025-02-03T09:00:00Z',
    profile_image: 'https://example.com/uploads/patients/fatima-alfarsi.jpg',
    preferred_language: 'ar',
    contact_preference: 'sms',
    emergency_contact: {
      name: 'Amina Al-Farsi',
      relation: 'sister',
      phone: '+44-20-7946-0950',
    },
    notes: 'Recently immigrated; translation support recommended. History of asthma.',
    files: [],
    appointments: ['apt-2025-02-10-012'],
    medical_flags: ['asthma'],
    allergies: [
      {
        substance: 'dust mites',
        reaction: 'shortness of breath',
        severity: 'moderate',
      },
    ],
    medications: [
      {
        name: 'Salbutamol',
        dosage: 'as needed',
        start_date: '2024-12-01',
        end_date: '2025-12-01',
        prescribed_by: 'dr-302',
      },
    ],
    conditions: ['asthma'],
    consent_to_contact: true,
    consent_signed_date: '2025-02-03',
    status: 'active',
    tags: ['new-patient', 'language-support'],
  },
  {
    id: 'f531f0b0-13e6-4d52-bbd7-2e2efc4c4a3c',
    first_name: 'Liam',
    last_name: 'Kowalski',
    email: 'liam.kowalski@example.com',
    phone: '+49-30-1234-5678',
    gender: 'male',
    birth_date: '2003-11-18',
    address: {
      street: 'Grunewaldstraße 8',
      city: 'Berlin',
      zip_code: '10823',
    },
    national_id: 'DE1102983476',
    insurance_number: 'GKV-2025-3312',
    registration_date: '2025-06-01T11:15:00Z',
    profile_image: 'https://example.com/uploads/patients/liam-kowalski.jpg',
    preferred_language: 'de',
    contact_preference: 'sms',
    emergency_contact: {
      name: 'Anna Kowalski',
      relation: 'mother',
      phone: '+49-30-2345-6789',
    },
    notes: 'Student. Came in for sports injury. No known chronic issues.',
    files: ['https://example.com/files/xray_ankle_liam_2025.jpg'],
    appointments: ['apt-2025-06-02-001'],
    medical_flags: [],
    allergies: [],
    medications: [],
    conditions: [],
    consent_to_contact: true,
    consent_signed_date: '2025-06-01',
    status: 'active',
    tags: ['student', 'sports'],
  },
];

async function emit_fetchPatients(): Promise<Patient[]> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(patients), 1000);
  });
}

export default emit_fetchPatients;
